### ISSUE TITLE
problem about  np.get_gpus() 

### ISSUE THREAD

**Issue by Irvingwangjr** [JiahuiYu/neuralgym#4]
hi jiahui,i'am using your inpainting test model. when the code comes to this np.get_gpus(1) line, an weird error happen.
![42c09b862b5bacffad36b09f79e1b69](https://user-images.githubusercontent.com/32162780/43141652-05c4860c-8f89-11e8-86f0-fa36c0ec0ad3.png)

i was wandering whether my environment was wrong: i'm using anaconda2 with py3.5 +cuda9.0+cudnn7.1
my GPU is 1050Ti.

**Comment by JiahuiYu** [comment]
Just remove that line. The reason is because Xorg and other programs are taken up your GPU. ng.get_gpus(1) will automatically get one FREE gpu.
